### ISSUE TITLE
Pinta rectangles grisos al selector de pinzells. Cal que no els pinti.

### ISSUE THREAD

**Issue by miquelsoler** [miquelsoler/Cancons-Visuals#3]
De vegades pinta rectangles grisos al selector de pinzells:
![2015-12-11](https://cloud.githubusercontent.com/assets/1842840/11785845/e660f600-a283-11e5-94bf-b296a05a987c.png)
![2015-12-11-1](https://cloud.githubusercontent.com/assets/1842840/11785847/e89ec014-a283-11e5-9b18-55c6ba692a77.png)
![2015-12-11-2](https://cloud.githubusercontent.com/assets/1842840/11785849/e9c2b838-a283-11e5-82c5-fb84854f32cd.png)
![2015-12-11-3](https://cloud.githubusercontent.com/assets/1842840/11785854/eae39520-a283-11e5-8988-4a036044876c.png)

**Comment by miquelsoler** [comment]
@eduardfrigola Això es va resoldre?

**Comment by eduardfrigola** [comment]
Es va resoldre, era culpa que tenia una carpeta que era compartida, i apart dels png dels pinzells tenia l'icono de la carpeta, i aixo el feia tornar boig

**Comment by miquelsoler** [comment]
Bé! Igualment era un exemple de bug. :)
