### ISSUE TITLE
Kinect detection

### ISSUE THREAD

**Issue by eduardfrigola** [miquelsoler/Cancons-Visuals#6]
Seems that it does not get the first person in the scene.

**Comment by eduardfrigola** [comment]
Fix also kinect on off on bucle

**Comment by xavibove** [comment]
Veig que estas online…

A la versió de Nacho, no caldria la selecció de pinzells…

Al meu ordinador no sona… a veure si amb una tarja externa o algo….

Veig sols una de les layers, on es canvia?

Demà podrà anar la teva versió també?

Salut!

**Comment by eduardfrigola** [comment]
Vas fer allo de descarregar els controladors per al teu mac? Si no ho vas fer, descarregat-ho i dema o instalem.

Faig que es salti els pinzells a la versió nacho. També he vist que sols va un pizell a la seva versio per aixo et preguntava si ell ho sabia que hi anava la seva versió.

Perque vagi la meva versió hauria de fer els canvis de detecció kinect, imprimir i altres histories que he anat modificant. Demà al tren ho faig, que pude millor ara que vagi a descansar...

Eduard Frigola

El 25 maig 2016, a les 23:47, Xavi Bove notifications@github.com va escriure:
